/**
 * Created by idris on 6/2/15.
 */
/*
 * this block is shared between client and server
 */
var currentPlayer, gameSummary, getWinner;


Cells = new Meteor.Collection('cells');
Players = new Meteor.Collection('players');
Rooms = new Meteor.Collection('rooms');

gameSummary = function(roomId) {
    var cell, combo, key, pickedCells, pickedWinningCombo, val, winners, winningCombos, _i, _j, _len, _len1, _name, _ref;
    winningCombos = [
        ['0', '1', '2'],
        ['3', '4', '5'],
        ['6', '7', '8'],
        ['0', '3', '6'],
        ['1', '4', '7'],
        ['2', '5', '8'],
        ['0', '4', '8'],
        ['2', '4', '6']
    ];
    pickedCells = {};
    _ref = Cells.find({roomId:roomId}).fetch();
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        cell = _ref[_i];
        if (cell.type != null) {
            if (pickedCells[_name = cell.type] == null) {
                pickedCells[_name] = [];
            }
            pickedCells[cell.type].push(cell._id);
        }
    }
    winners = {};
    for (key in pickedCells) {
        val = pickedCells[key];
        for (_j = 0, _len1 = winningCombos.length; _j < _len1; _j++) {
            combo = winningCombos[_j];
            pickedWinningCombo = _.all(combo, function(comboItem) {
                return _.contains(pickedCells[key], comboItem);
            });
            if (pickedWinningCombo) {
                winners[key] = true;
                winners.winningCells = combo;
            }
        }
    }
    return winners;
};


/*
 * client only block -- should be in a 'client' folder
 */

if (Meteor.isClient) {

    turn=0;
    currentPlayer = function() {
        if ((Cells.find({$and:[{type: {$exists: true  } },{roomId:Session.get('roomId')}]}, { sort: {_id: 1} }).count() % 2) === 0) {
            return 'X';
        } else {
            return 'O';
        }

        if(turn % 2 === 0)
            Session.set('cellStatus','cellOn');
        else
            Session.set('cellStatus','cellOff');

    };

    getWinner = function() {
        var key, val, _ref;
        _ref = gameSummary(Session.get('roomId'));
        for (key in _ref) {
            val = _ref[key];
            if (val === true) {
                return key;
            }
        }
        return false;
    };

    Template.board.helpers({
        currentPlayer: function() {
            return currentPlayer();
        },
        winner: function() {
            return getWinner();
        },
        cellState: function(){

          return Session.get('cellStatus');
        },
        cells: function() {
            return Cells.find({roomId:Session.get('roomId')}, { sort: { _id: 1 } });
        },
        buttonType: function() {
            if (this.winning) {
                return 'btn-success';
            } else if (this.type != null) {
                return 'btn-primary';
            } else {
                return 'btn-default';
            }
        }
    });
    Template.board.events({
        'click .restart-game': function() {
            return Meteor.call('restartGame',Session.get('roomId'));
        },
        'click .cell': function() {
          //  Session.set('cellStatus','cellOff');
            turn=turn+1;

            var _ref;
            if (!((((_ref = Cells.findOne({$and:[{_id: this._id },{roomId:Session.get('roomId')}]})) != null ? _ref.type : void 0) != null) || getWinner()))
            {
                var docid=Cells.findOne({$and:[{_id: this._id },{roomId:Session.get('roomId')}]});
                Cells.update({_id:docid._id}, {$set: {type: currentPlayer()}});
                if (gameSummary(Session.get('roomId')).winningCells != null) {
                   return Meteor.call('updateWinningCells',Session.get('roomId'));

                }
            }
        }
    });
}


/*
 * server only block -- should be in a a 'server' folder
 */

if (Meteor.isServer) {
    Meteor.methods({
        'restartGame': function(roomId)
        {
            return Cells.update({roomId:roomId}, {$unset: {  type: true, winning: true }}, { multi: true });
        },
        'updateWinningCells': function(roomId) {
            if (gameSummary(roomId).winningCells != null)
            {
                return Cells.update({$and:[{ _id: {$in: gameSummary(roomId).winningCells }},{roomId:roomId}]}, { $set: { winning: true } }, { multi: true});
            }
        }
    });

    Meteor.startup(function() {
        /*var i;
       if (Cells.find().count() === 0)
        {
            for (i  = 0; i <= 8; i = ++i) {
                Cells.insert({ _id: "" + i});
            }
          //  return _results;
        }*/


    });
}

// ---
// generated by coffee-script 1.9.0